spring:
  #config:
    #import: configserver
  application:
    name: greeting-service
greeting-service:
  greeting: "ola"
  default-value: "dev"
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

